name: uavbook
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.10
    - pip
    - numpy
    - matplotlib
    - jupyter
    - scipy
    - opencv
    - pillow
    - pyqt
    - pyqtgraph
    - pyopengl
    - python-dotenv
    - pip:
        - pynput
