function [T_phi_delta_a,...
          T_chi_phi,...
          T_theta_delta_e,...
          T_h_theta,...
          T_h_Va,...
          T_Va_delta_t,...
          T_Va_theta,...
          T_v_delta_r]...
          = compute_tf_model(x_trim,u_trim,P)
end

% returns the derivative of motor thrust with respect to Va
function dThurst = dT_dVa(mav, Va, delta_t)
end

% returns the derivative of motor thrust with respect to delta_t
function dThurst = dT_ddelta_t(mav, Va, delta_t)
end